#!/usr/bin/env python
"""KnowLP task-state modulation layer — TaskState + TaskModulator (v0 heuristic)

Architecture constraints (docs/task-state-modulation-design.md §0.0): KnowLP is the retrieval
memory layer sitting on top of all storage. This module is **storage-agnostic**: it does not
import config, nor read dual_graph.json / meta_index.json / any backend. Profile dims (tags/dir)
are extracted from storage by the caller's adapter and passed in.
v0 scope (B before A; B = peripheral gain multiply, rollback-safe):
- no training; heuristic/rule-based
- TaskState: session-level EMA state slot (dict over dims, dynamic vocab, no np.ndarray)
- TaskModulator.modulate: query + candidate_dims + state -> {node: gain}
- TaskModulator.apply: multiply gain into merged rank_score
- state None -> all 1.0 (bit-identical to the status quo, rollback-safe)

Focus semantics (maps to paper FiLM = per-query modulation + Recurrent State = historical focus):
- query literally hits a profile dim → that dim is the current task domain → instant boost (anti-crossover; history yields)
- query has no clear domain → fall back to historical focus (state boost / off-focus damping)
Corresponding soft mask: ω = clip(ρ·γ, [0.3, 2.0]).
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field


GAIN_MIN = 0.3
GAIN_MAX = 2.0
QUERY_BOOST = 1.5   # query instant-hit (FiLM heuristic) boost
STATE_BOOST = 0.5   # state-history hit boost slope: gain = 1 + 0.5 * min(s_hit, 2)
OFF_FOCUS = 0.7     # off-focus damping (soft)
FADE_EPS = 0.05     # EMA fade threshold; dims below it are dropped


@dataclass
class TaskState:
    """Session-level task-state slot.

    mu: dim → accumulated focus weight (EMA). Dynamic vocab, no np.ndarray (dims have no fixed vocab).
    dim can be a tag (e.g. "stocks") or a dir label (e.g. "dir:destiny", generated by the adapter).
    """
    session_id: str
    mu: dict = field(default_factory=dict)
    count: int = 0
    window: int = 5
    last_ts: float = field(default_factory=time.time)

    def update(self, focus_dims: dict[str, float], alpha: float = 0.3) -> None:
        """EMA update: mu = alpha*new + (1-alpha)*mu. Untouched dims fade by (1-alpha)."""
        for d, w in focus_dims.items():
            self.mu[d] = alpha * w + (1 - alpha) * self.mu.get(d, 0.0)
        for d in list(self.mu.keys()):
            if d not in focus_dims:
                self.mu[d] *= (1 - alpha)
                if self.mu[d] < FADE_EPS:
                    del self.mu[d]
        self.count += 1
        self.last_ts = time.time()

    def focus(self, top_k: int | None = None) -> dict[str, float]:
        """Current focus zone: top-k dims of mu in descending weight (None = all non-zero)."""
        ranked = sorted(self.mu.items(), key=lambda kv: -kv[1])
        if top_k is not None:
            ranked = ranked[:top_k]
        return {d: w for d, w in ranked if w > 0}


class TaskModulator:
    """v0 heuristic modulator: query instant focus + task-state history focus → candidate node gains.

    Interface per design doc §2; candidate_dims is {node: [dim]}, provided by the storage adapter.
    """

    @staticmethod
    def _label(dim: str) -> str:
        """Strip the dir: prefix to get the literal label for literal query matching."""
        return dim[4:] if dim.startswith('dir:') else dim

    def modulate(self, query: str, candidate_dims: dict[str, list[str]],
                 state: TaskState | None) -> dict[str, float]:
        """Return {node: gain}, gain ∈ [GAIN_MIN, GAIN_MAX].

        state None -> all 1.0 (rollback-safe).
        Query literally hits a dim → instant focus wins (anti-crossover: old state does not lift when switching domains);
        query has no clear domain → state-history focus is the fallback.
        """
        if state is None:
            return {name: 1.0 for name in candidate_dims}

        q = (query or '').lower()
        all_dims = {d for dims in candidate_dims.values() for d in (dims or [])}
        q_dims = {d for d in all_dims if self._label(d) and self._label(d).lower() in q}
        focus = state.focus()

        gains: dict[str, float] = {}
        for name, dims in candidate_dims.items():
            dims = dims or []
            if q_dims:
                # query has a clear domain: instant focus first, history yields (anti-crossover)
                if any(d in q_dims for d in dims):
                    g = QUERY_BOOST
                elif dims:
                    g = OFF_FOCUS
                else:
                    g = 1.0
            else:
                # query has no clear domain: state-history focus is the fallback
                s_hit = sum(focus.get(d, 0.0) for d in dims)
                if s_hit > 0:
                    g = 1.0 + STATE_BOOST * min(s_hit, 2.0)
                elif dims:
                    g = OFF_FOCUS
                else:
                    g = 1.0
            gains[name] = round(min(GAIN_MAX, max(GAIN_MIN, g)), 4)
        return gains

    def apply(self, merged: list[dict], gains: dict[str, float]) -> list[dict]:
        """Multiply gain into each item's rank_score (in place). name missing from gains -> 1.0, untouched."""
        for r in merged:
            g = gains.get(r.get('name'), 1.0)
            if 'rank_score' in r:
                r['rank_score'] = r['rank_score'] * g
        return merged
