#!/usr/bin/env python
"""KnowLP task-state modulation layer — TaskState + TaskModulator (v0 heuristic)

Architecture constraints (docs/task-state-modulation-design.md §0.0): KnowLP is the retrieval
memory layer sitting on top of all storage. This module is **storage-agnostic**: it does not
import config, nor read dual_graph.json / meta_index.json / any backend. Profile dims (tags/dir)
are extracted from storage by the caller's adapter and passed in.
v0 scope (B before A; B = peripheral gain multiply, rollback-safe):
- no training; heuristic/rule-based
- TaskState: session-level EMA state slot (dict over dims, dynamic vocab, no np.ndarray)
- TaskModulator.modulate: query + candidate_dims + state -> {node: gain}
- TaskModulator.apply: multiply gain into merged rank_score
- TaskModulator.authorize: soft action-authority hints (Palantir governed-surface alignment)
- state None -> all 1.0 (bit-identical to the status quo, rollback-safe)

Focus semantics (maps to paper FiLM = per-query modulation + Recurrent State = historical focus):
- query literally hits a profile dim → that dim is the current task domain → instant boost (anti-crossover; history yields)
- query has no clear domain → fall back to historical focus (state boost / off-focus damping)
Corresponding soft mask: ω = clip(ρ·γ, [0.3, 2.0]).
"""
from __future__ import annotations

import time
from collections import Counter
from dataclasses import dataclass, field


GAIN_MIN = 0.3
GAIN_MAX = 2.0
QUERY_BOOST = 1.5   # query instant-hit (FiLM heuristic) boost
STATE_BOOST = 0.5   # state-history hit boost slope: gain = 1 + 0.5 * min(s_hit, 2)
OFF_FOCUS = 0.7     # off-focus damping (soft)
FADE_EPS = 0.05     # EMA fade threshold; dims below it are dropped
AUTHORITY_CAP = 4   # max action scopes per retrieval (governed-subset: keep the surface small)


@dataclass
class TaskState:
    """Session-level task-state slot.

    mu: dim → accumulated focus weight (EMA). Dynamic vocab, no np.ndarray (dims have no fixed vocab).
    dim can be a tag (e.g. "stocks") or a dir label (e.g. "dir:destiny", generated by the adapter).
    """
    session_id: str
    mu: dict = field(default_factory=dict)
    count: int = 0
    window: int = 5
    last_ts: float = field(default_factory=time.time)

    def update(self, focus_dims: dict[str, float], alpha: float = 0.3) -> None:
        """EMA update: mu = alpha*new + (1-alpha)*mu. Untouched dims fade by (1-alpha)."""
        for d, w in focus_dims.items():
            self.mu[d] = alpha * w + (1 - alpha) * self.mu.get(d, 0.0)
        for d in list(self.mu.keys()):
            if d not in focus_dims:
                self.mu[d] *= (1 - alpha)
                if self.mu[d] < FADE_EPS:
                    del self.mu[d]
        self.count += 1
        self.last_ts = time.time()

    def focus(self, top_k: int | None = None) -> dict[str, float]:
        """Current focus zone: top-k dims of mu in descending weight (None = all non-zero)."""
        ranked = sorted(self.mu.items(), key=lambda kv: -kv[1])
        if top_k is not None:
            ranked = ranked[:top_k]
        return {d: w for d, w in ranked if w > 0}


class TaskModulator:
    """v0 heuristic modulator: query instant focus + task-state history focus → candidate node gains.

    Interface per design doc §2; candidate_dims is {node: [dim]}, provided by the storage adapter.
    """

    @staticmethod
    def _label(dim: str) -> str:
        """Strip the dir: prefix to get the literal label for literal query matching."""
        return dim[4:] if dim.startswith('dir:') else dim

    def modulate(self, query: str, candidate_dims: dict[str, list[str]],
                 state: TaskState | None) -> dict[str, float]:
        """Return {node: gain}, gain ∈ [GAIN_MIN, GAIN_MAX].

        state None -> all 1.0 (rollback-safe).
        Query literally hits a dim → instant focus wins (anti-crossover: old state does not lift when switching domains);
        query has no clear domain → state-history focus is the fallback.
        """
        if state is None:
            return {name: 1.0 for name in candidate_dims}

        q = (query or '').lower()
        all_dims = {d for dims in candidate_dims.values() for d in (dims or [])}
        q_dims = {d for d in all_dims if self._label(d) and self._label(d).lower() in q}
        focus = state.focus()

        gains: dict[str, float] = {}
        for name, dims in candidate_dims.items():
            dims = dims or []
            if q_dims:
                # query has a clear domain: instant focus first, history yields (anti-crossover)
                if any(d in q_dims for d in dims):
                    g = QUERY_BOOST
                elif dims:
                    g = OFF_FOCUS
                else:
                    g = 1.0
            else:
                # query has no clear domain: state-history focus is the fallback
                s_hit = sum(focus.get(d, 0.0) for d in dims)
                if s_hit > 0:
                    g = 1.0 + STATE_BOOST * min(s_hit, 2.0)
                elif dims:
                    g = OFF_FOCUS
                else:
                    g = 1.0
            gains[name] = round(min(GAIN_MAX, max(GAIN_MIN, g)), 4)
        return gains

    def apply(self, merged: list[dict], gains: dict[str, float]) -> list[dict]:
        """Multiply gain into each item's rank_score (in place). name missing from gains -> 1.0, untouched."""
        for r in merged:
            g = gains.get(r.get('name'), 1.0)
            if 'rank_score' in r:
                r['rank_score'] = r['rank_score'] * g
        return merged


@dataclass
class ActionPolicy:
    """Dim label → allowed action scopes. Injected by the caller (storage-agnostic, §0.0).

    Example: {"stocks": {"search", "record_feedback"},
              "office": {"excel_recalc", "excel_vba_run"}}
    Empty/None policy → authorize() returns empty hints (bit-identical to the status quo).

    Design (Palantir AIP governed-surface alignment, docs/AI技术跟踪-Palantir AIP架构.md §二):
    the agent never sees the whole action surface — only the scopes this retrieval's
    dims justify. v0 is SOFT: hints only, no enforcement; the MCP layer decides.
    """

    policy: dict = field(default_factory=dict)
    max_scopes: int = AUTHORITY_CAP


def _norm_label(dim: str) -> str:
    """Shared label normalizer (strips the dir: prefix, lowercases)."""
    d = dim[4:] if dim.startswith('dir:') else dim
    return d.lower()


class ActionAuthorizer:
    """Derives the governed action surface for one retrieval, from three sources
    (mirroring TaskModulator.modulate's dual-path semantics):

      1. query literally hits a dim label → its scopes (instant, anti-crossover)
      2. retrieved nodes' dims → their scopes (evidence-backed)
      3. state-history focus dims → their scopes (fallback)

    Union is capped at policy.max_scopes, ranked by (query-hit first, then
    cross-node frequency) — the Palantir "governed subset" idea at retrieval speed.
    """

    def __init__(self, modulator: TaskModulator | None = None):
        self.modulator = modulator or TaskModulator()

    def authorize(self, query: str, retrieved: list[str],
                  candidate_dims: dict[str, list[str]],
                  state: TaskState | None,
                  policy: ActionPolicy | None) -> dict:
        """Soft action-authority hints. No policy / empty policy → empty result
        (bit-identical to the status quo; the MCP layer treats empty as "no hints")."""
        if not policy or not policy.policy:
            return {"scopes": [], "per_node": {}, "capped": False}

        label_scopes = {self.modulator._label(d).lower(): set(scopes or ())
                        for d, scopes in policy.policy.items()}
        q = (query or '').lower()
        q_hit_labels = {lbl for lbl in label_scopes if lbl and lbl in q}

        retrieved = retrieved or []
        per_node_scopes: dict[str, set] = {}
        for name in retrieved:
            dims = {_norm_label(d) for d in (candidate_dims.get(name) or [])}
            scopes = set()
            if q_hit_labels:
                scopes |= set().union(*(label_scopes[l] for l in q_hit_labels))
            scopes |= set().union(*(label_scopes[l] for l in dims if l in label_scopes)) \
                if dims else set()
            if state:
                for d in state.focus():
                    lbl = _norm_label(d)
                    if lbl in label_scopes:
                        scopes |= label_scopes[lbl]
            per_node_scopes[name] = scopes

        all_scopes = set().union(*per_node_scopes.values()) if per_node_scopes else set()
        q_hit_scopes = set().union(*(label_scopes[l] for l in q_hit_labels)) if q_hit_labels else set()
        freq = Counter()
        for scopes in per_node_scopes.values():
            freq.update(scopes)
        capped = len(all_scopes) > policy.max_scopes
        kept = set(sorted(all_scopes,
                          key=lambda s: (-(s in q_hit_scopes), -freq[s], s))[:policy.max_scopes])
        per_node = {n: sorted(sc & kept) for n, sc in per_node_scopes.items()}
        return {"scopes": sorted(kept), "per_node": per_node, "capped": capped}
